# Generated by Django 3.2.16 on 2023-02-01 20:04

import api.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20230129_0118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(default='+79876543210', max_length=14, validators=[api.validators.regex_check_number], verbose_name='Номер телефона'),
            preserve_default=False,
        ),
    ]
