# Generated by Django 3.2.16 on 2023-02-02 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20230201_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(error_messages={'unique': 'Пользоватль с таким адресом электронной почты уже существует.'}, max_length=50, unique=True, verbose_name='Электронная почта'),
        ),
    ]
