# Generated by Django 3.2.16 on 2023-02-12 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('users', '0005_auto_20230204_0001')]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(
                error_messages={
                    'unique': (
                        'Пользователь с таким адресом электронной почты '
                        'уже существует.'
                    )
                },
                max_length=50,
                unique=True,
                verbose_name='Электронная почта',
            ),
        )
    ]
