# Generated by Django 3.2.16 on 2023-02-26 18:02

import django.core.validators
from django.db import migrations, models

import api.validators


class Migration(migrations.Migration):

    dependencies = [('users', '0006_alter_user_email')]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(
                max_length=30,
                validators=[
                    api.validators.validate_name,
                    django.core.validators.MinLengthValidator(
                        2, 'Имя должно быть минимум 2 символа в длину.'
                    ),
                ],
                verbose_name='Имя',
            ),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(
                max_length=30,
                validators=[
                    api.validators.validate_name,
                    django.core.validators.MinLengthValidator(
                        2, 'Фамилия должна быть минимум 2 символа в длину.'
                    ),
                ],
                verbose_name='Фамилия',
            ),
        ),
    ]
