# Generated by Django 3.2.16 on 2022-12-26 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('price', models.IntegerField()),
                ('area', models.IntegerField()),
                ('floor', models.IntegerField()),
                ('year', models.IntegerField()),
                ('desc', models.TextField()),
                ('image', models.ImageField(blank=True, default='', null=True, upload_to='flats/images/')),
            ],
        ),
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('area', models.CharField(choices=[(1, 'Анталия'), (2, 'Стамбул'), (3, 'Северный Кипр')], max_length=50)),
                ('type', models.CharField(choices=[(1, 'Участок'), (2, 'Студия'), (3, 'Квартира'), (4, 'Вилла')], max_length=50)),
                ('room', models.IntegerField(choices=[(1, 0), (2, 1), (3, 2), (4, 3), (5, 4)])),
                ('flat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rent', to='flats.flat')),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='flats/images/', verbose_name='Фото')),
                ('flat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='img', to='flats.flat')),
            ],
        ),
        migrations.CreateModel(
            name='Buy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('status', models.CharField(choices=[(1, 'Новостройка'), (2, 'Вторичное')], max_length=30)),
                ('area', models.CharField(choices=[(1, 'Анталия'), (2, 'Стамбул'), (3, 'Северный Кипр')], max_length=50)),
                ('type', models.CharField(choices=[(1, 'Участок'), (2, 'Студия'), (3, 'Квартира'), (4, 'Вилла')], max_length=50)),
                ('room', models.IntegerField(choices=[(1, 0), (2, 1), (3, 2), (4, 3), (5, 4)])),
                ('flat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buy', to='flats.flat')),
            ],
        ),
    ]
