# Generated by Django 3.2.16 on 2022-12-27 06:04

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Электронная почта')),
                ('first_name', models.CharField(max_length=200, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=200, verbose_name='Фамилия')),
                ('phone_number', phone_field.models.PhoneField(max_length=31, unique=True, verbose_name='Номер телефона')),
                ('agreement', models.BooleanField(default=False, verbose_name='Согласие')),
                ('role', models.CharField(choices=[('seller', 'seller'), ('buyer', 'buyer')], default='seller', max_length=6)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
