# Generated by Django 3.2.16 on 2023-02-02 21:02

import api.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='phone',
            field=models.CharField(max_length=50, validators=[api.validators.regex_check_number], verbose_name='Телефон'),
        ),
    ]
