# Generated by Django 3.2.16 on 2023-02-12 16:53

from django.db import migrations, models

import api.validators


class Migration(migrations.Migration):

    dependencies = [('about', '0002_alter_team_phone')]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='phone',
            field=models.CharField(
                max_length=14,
                validators=[api.validators.regex_check_number],
                verbose_name='Телефон',
            ),
        )
    ]
