# Generated by Django 3.2.16 on 2023-01-28 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Аренда', 'Аренда'), ('Продажа', 'Продажа')], db_index=True, default='Аренда', max_length=7, unique=True, verbose_name='Категория объекта')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('icon', models.SlugField(max_length=100, verbose_name='Иконка')),
            ],
            options={
                'verbose_name': 'Удобство',
                'verbose_name_plural': 'Удобства',
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'Избранное',
                'verbose_name_plural': 'Избранное',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='real_estate', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Фотография',
                'verbose_name_plural': 'Фотографии',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Слаг')),
            ],
            options={
                'verbose_name': 'Локация',
                'verbose_name_plural': 'Локации',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rooms', models.SmallIntegerField(blank=True, default=1, null=True, verbose_name='Количество комнат')),
                ('first_name', models.CharField(max_length=30, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=30, verbose_name='Фамилия')),
                ('phone_number', models.CharField(max_length=14, unique=True, verbose_name='Номер телефона')),
                ('email', models.EmailField(max_length=50, unique=True, verbose_name='Электронная почта')),
                ('comment', models.TextField(blank=True, max_length=200, null=True, verbose_name='Комментарии')),
                ('agreement', models.BooleanField(default=False, verbose_name='Согласие')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('confirmation_code', models.CharField(max_length=32, verbose_name='Код подтверждения.')),
                ('confirmed', models.BooleanField(default=False, verbose_name='Подтверждение')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
            },
        ),
        migrations.CreateModel(
            name='PropertyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Тип недвижимости',
                'verbose_name_plural': 'Типы недвижимости',
            },
        ),
        migrations.CreateModel(
            name='RealEstate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('area', models.IntegerField(verbose_name='Площадь')),
                ('floor', models.IntegerField(blank=True, null=True, verbose_name='Этаж')),
                ('total_floors', models.IntegerField(blank=True, null=True, verbose_name='Этажность')),
                ('construction_year', models.IntegerField(blank=True, null=True, verbose_name='Год постройки')),
                ('rooms', models.SmallIntegerField(blank=True, null=True, verbose_name='Количество комнат')),
                ('date_added', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата добавления')),
                ('status', models.CharField(choices=[('Новостройка', 'Новостройка'), ('Вторичное', 'Вторичное')], db_index=True, default='Новостройка', max_length=11, verbose_name='Статус')),
                ('currency', models.CharField(choices=[('₺', '₺'), ('$', '$'), ('€', '€'), ('₽', '₽')], default='₺', max_length=1, verbose_name='Валюта')),
                ('description', models.TextField(verbose_name='Описание')),
                ('period', models.CharField(choices=[('День', 'День'), ('Месяц', 'Месяц'), ('Год', 'Год')], default='Месяц', max_length=5, verbose_name='Период')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='real_estate', to='catalog.category', verbose_name='Категория')),
                ('facility', models.ManyToManyField(related_name='real_estate', to='catalog.Facility', verbose_name='Удобства')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='real_estate', to='catalog.location', verbose_name='Локация')),
            ],
            options={
                'verbose_name': 'Объект',
                'verbose_name_plural': 'Объекты',
            },
        ),
    ]
