# Generated by Django 3.2.16 on 2023-02-01 20:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20230201_2304'),
    ]

    operations = [
        migrations.RenameField(
            model_name='realestate',
            old_name='type',
            new_name='property_type',
        ),
        migrations.AlterField(
            model_name='order',
            name='rooms',
            field=models.PositiveSmallIntegerField(blank=True, default=1, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество комнат'),
        ),
        migrations.AlterField(
            model_name='realestate',
            name='area',
            field=models.PositiveIntegerField(verbose_name='Площадь'),
        ),
        migrations.AlterField(
            model_name='realestate',
            name='price',
            field=models.PositiveIntegerField(verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='realestate',
            name='rooms',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество комнат'),
        ),
        migrations.AlterField(
            model_name='realestate',
            name='total_floors',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Этажность'),
        ),
    ]
