# Generated by Django 3.2.16 on 2023-02-05 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20230201_2321'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ('-id',), 'verbose_name': 'Фотография', 'verbose_name_plural': 'Фотографии'},
        ),
        migrations.AlterModelOptions(
            name='realestate',
            options={'ordering': ('-date_added',), 'verbose_name': 'Объект', 'verbose_name_plural': 'Объекты'},
        ),
    ]
