# Generated by Django 3.2.16 on 2023-02-12 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('catalog', '0006_auto_20230205_2016')]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_sent',
            field=models.BooleanField(
                default=False, verbose_name='Отправлено'
            ),
        )
    ]
