# Generated by Django 3.2.16 on 2023-03-03 20:45

from django.db import migrations, models

import catalog.models


class Migration(migrations.Migration):

    dependencies = [('catalog', '0007_order_is_sent')]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(
                choices=[('Аренда', 'Аренда'), ('Покупка', 'Покупка')],
                db_index=True,
                default='Аренда',
                max_length=7,
                unique=True,
                verbose_name='Категория объекта',
            ),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(
                upload_to=catalog.models.folder_path, verbose_name='Фото'
            ),
        ),
    ]
