# Generated by Django 3.2.16 on 2023-02-28 07:30

import catalog.models
from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_order_is_sent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('Аренда', 'Аренда'), ('Покупка', 'Покупка')], db_index=True, default='Аренда', max_length=7, unique=True, verbose_name='Категория объекта'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format='JPEG', keep_meta=True, quality=75, scale=None, size=(738, 632), upload_to=catalog.models.folder_path, verbose_name='Фото'),
        ),
    ]
