# Generated by Django 3.2.16 on 2023-03-13 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [('catalog', '0008_auto_20230303_2345')]

    operations = [
        migrations.RemoveField(model_name='order', name='category'),
        migrations.RemoveField(model_name='order', name='location'),
        migrations.RemoveField(model_name='order', name='property_type'),
        migrations.AlterField(
            model_name='order',
            name='rooms',
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name='Количество комнат',
            ),
        ),
        migrations.CreateModel(
            name='OrderPropertyType',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'order',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='orderpropertytype',
                        to='catalog.order',
                    ),
                ),
                (
                    'property_type',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='orderpropertytype',
                        to='catalog.propertytype',
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='OrderLocation',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'location',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='orderlocation',
                        to='catalog.location',
                    ),
                ),
                (
                    'order',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='orderlocation',
                        to='catalog.order',
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='OrderCategory',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'category',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='ordercategory',
                        to='catalog.category',
                    ),
                ),
                (
                    'order',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='ordercategory',
                        to='catalog.order',
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='category',
            field=models.ManyToManyField(
                related_name='orders',
                through='catalog.OrderCategory',
                to='catalog.Category',
                verbose_name='Аренда/Покупка',
            ),
        ),
        migrations.AddField(
            model_name='order',
            name='location',
            field=models.ManyToManyField(
                blank=True,
                related_name='orders',
                through='catalog.OrderLocation',
                to='catalog.Location',
                verbose_name='Локация',
            ),
        ),
        migrations.AddField(
            model_name='order',
            name='property_type',
            field=models.ManyToManyField(
                blank=True,
                related_name='orders',
                through='catalog.OrderPropertyType',
                to='catalog.PropertyType',
                verbose_name='Тип недвижимости',
            ),
        ),
    ]
