# Generated by Django 3.2.18 on 2023-05-05 12:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('catalog', '0009_auto_20230314_0044'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_reviewed',
            field=models.BooleanField(default=False, verbose_name='Ответ'),
        ),
        migrations.AddField(
            model_name='order',
            name='review_date',
            field=models.DateField(
                blank=True, null=True, verbose_name='Дата ответа'
            ),
        ),
    ]
