# Generated by Django 3.2.18 on 2023-05-05 13:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('catalog', '0010_auto_20230505_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_added',
            field=models.DateTimeField(
                auto_now_add=True, verbose_name='Дата заявки'
            ),
        ),
    ]
