openapi: 3.1.0
x-stoplight:
  id: ijt9bixg78e2t
info:
  title: AntalyaDom
  version: '1.0'
  summary: API для фронтенда <> бэкэнда
  contact:
    email: rp@telfia.com
    name: Roman Petrakov
    url: 'https://github.com/spaut33/'
servers:
  - url: /api
    description: ''
paths:
  /users/profile/:
    get:
      summary: Профиль пользователя
      tags: []
      responses:
        '200':
          description: OK
        '401':
          description: Unauthorized
      operationId: get-users-profile
      description: ''
      security:
        - Token: []
      parameters: []
    parameters: []
components:
  schemas:
    User:
      title: User
      x-stoplight:
        id: h6htg2x8ev70e
      type: object
      properties:
        id:
          type: string
        first_name:
          type: string
          maxLength: 30
        last_name:
          type: string
          maxLength: 30
        email:
          type: string
          format: email
        password:
          type: string
          format: password
        phone:
          type: string
          minLength: 10
          maxLength: 14
          pattern: '^\+?[0-9]+'
          example: '+79217779900'
        agreement:
          type: boolean
          default: false
        role:
          type: string
          deprecated: true
    Favorite:
      title: Favorite
      x-stoplight:
        id: 84df6k6665p3u
      type: object
      properties:
        id:
          type: string
        object:
          type: string
        user:
          type: string
        date_added:
          type: string
          format: date-time
    Object:
      title: Object
      x-stoplight:
        id: n7i136qerr65c
      type: object
      properties:
        id:
          type: string
    Category:
      title: Category
      x-stoplight:
        id: 0u2axaq6mnku2
      type: object
      examples:
        - id: string
          name: rent
      properties:
        id:
          type: string
          readOnly: true
        name:
          type: string
          default: rent
      description: ''
  securitySchemes:
    Token:
      type: http
      scheme: basic
      description: Авторизация по токену
security:
  - Token: []
