# Generated by Django 3.2.16 on 2022-12-26 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Flat',
            new_name='Estate',
        ),
    ]
