name: Deploy api documentation to the test server

on:
  push:
    branches:
      - docs
      - apidocs
      - feature/apidocs
      - feature/docs
      - dev

jobs:
    deploy:
        name: Deploy to test server
        runs-on: ubuntu-20.04
        steps:
        - name: Executing remote ssh commands to deploy
          uses: appleboy/ssh-action@master
          with:
            host: ${{ secrets.DEV_HOST }}
            username: ${{ secrets.DEV_USER }}
            key: ${{ secrets.DEV_KEY }}
            port: ${{ secrets.DEV_PORT }}
            script: |
              cd /home/antalia-dom/infra
              git fetch
              git checkout -m origin/${{ github.head_ref }} docs/
