name: Linting on PR and Push to dev and main

on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
      - dev
      - main

jobs:
  linting:
    name: Flake8 with plugins
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.8'
          cache: 'pip'
      - name: Upgrade pip
        run: python -m pip install --upgrade pip
      - name: Install dependencies
        run: |
          pip install flake8 pep8-naming flake8-broken-line flake8-return flake8-isort
      - name: Run linter
        run: |
          python -m flake8 .
  send_message:
    name: Sending notification
    runs-on: ubuntu-20.04
    needs: linting
    steps:
      - name: Send notification to telegram
        if: ${{ github.event_name == 'pull_request' }}
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TG_USER }}
          token: ${{ secrets.TG_TOKEN }}
          message: |
            ${{ github.actor }} открыл ${{ github.event_name }}
            ветки ${{ github.head_ref }} в ${{ github.base_ref }}
            репозитория ${{ github.repository }}.
            ${{ github.event.pull_request.html_url }}
