name: linting on pr and push to dev and main

on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
      - dev
      - main
  push:
    branches:
      - dev
      - main

jobs:
  tests:
    name: Python ${{ matrix.python-version }}
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.8'
          cache: 'pip'
      - name: Upgrade pip
        run: python -m pip install --upgrade pip
      - name: Install dependencies
        run: |
          pip install flake8 pep8-naming flake8-broken-line flake8-return flake8-isort
      - name: Run linter
        run: |
          python -m flake8 .
